# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/BadSpawns/issues"

[[mods]]
modId = "badspawns"
version = "${file.jarVersion}"
displayName = "BadSpawns"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/BadSpawns/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/BadSpawns"
logoFile= "../BadSpawns.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A server plugin to cancel the spawns of mobs you don't want
'''

# Forge Dependency
[[dependencies.badspawns]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.badspawns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
