name: BadSpawns
version: '${version}'
author: p0t4t0sandwich
description: A cross-API server plugin to cancel the spawns of mobs using defined regions and conditions.
main: dev.neuralnexus.badspawns.bukkit.BukkitBadSpawnsPlugin
depend: [TaterLib]
softdepend: [LuckPerms]
folia-supported: true
