---
version: 1
enabled: true
bannedMobs:
  - "modid:entityid"

regions:
    - name: ExampleRegion
      type: blacklist
      minX: -100
      maxX: *
      minY: 0
      maxY: *
      minZ: -100
      maxZ: *
      worlds:
        - world
      biomes:
        - "minecraft:plains"
      mobs:
        - "modid:entityid"

    - name: ExampleRegion2
      type: whitelist
      minX: -100
      maxX: 100
      minY: 0
      maxY: 256
      minZ: -100
      maxZ: 100
      worlds:
        - world
      biomes:
        - "minecraft:plains"
      mobs:
        - "modid:entityid"
