---
version: 1
enabled: true
bannedMobs:
  - "modid:entityid"

regions:
    - name: "ExampleRegion"
      type: "blacklist"
      minX: "-100"
      maxX: "*"
      minY: "0"
      maxY: "*"
      minZ: "-100"
      maxZ: "*"
      worlds:
        - "minecraft:overworld"
      biomes:
        - "minecraft:plains"
      mobs:
        - "modid:entityid"
