# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/BadSpawns/issues"

[[mods]]
modId = "badspawns"
version = "${file.jarVersion}"
displayName = "BadSpawns"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/BadSpawns/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/BadSpawns"
logoFile= "./BadSpawns.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A cross-API server plugin to cancel the spawns of mobs using defined regions and conditions.
'''

# Forge Dependency
[[dependencies.badspawns]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.badspawns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

# TaterLib Dependency
[[dependencies.badspawns]]
modId = "taterlib"
mandatory = true
versionRange = "[1.0.2,)"
ordering = "NONE"
side = "SERVER"

# LuckPerms Dependency
[[dependencies.badspawns]]
modId = "luckperms"
mandatory = false
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "SERVER"
